name: Angular CI/CD

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
    - name: Deploy to DigitalOcean
      uses: appleboy/ssh-action@master
      with:
        host: ${{secrets.IPSERVER}}
        username: ${{secrets.USER}}
        password: ${{secrets.CLAVESSH}}
        script: |
          cd /home/proyecto_figma
          git pull
          npm install
          npm install -g @angular/cli
          ng build
          if [ "${{secrets.IPSERVER}}" = "185.166.214.113" ]; then
            cp -r ./dist/figma/browser/* /var/www/vhosts/estamostrabajando.site/httpdocs
          else
            cp -r ./dist/figma/browser/* /var/www/html
          fi
