name: Angular CI/CD

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
    - name: Deploy to DigitalOcean
      uses: appleboy/ssh-action@master
      with:
        host: 165.227.102.141
        username: root
        password: ${{secrets.CLAVESSH}}
        script: |
          cd /home/proyecto_figma
          git pull
          npm install
          ng build
          cp -r ./dist/figma/browser/* /var/www/html
